accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('select/', views.select_room, name='select'),
    path('select/<str:room_name>/', views.chat_room, name='room'),
]

core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# from articles import views as article_views
from accounts import views as account_views


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    # path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('', account_views.signup_view, name="signup"),
    path('chat/', include('chat.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Room(models.Model):
    name = models.TextField(max_length=100)

    def __str__(self):
        return self.name


class Message(models.Model):
    room = models.ForeignKey('chat.Room', models.CASCADE)
    author = models.ForeignKey(
        User, related_name='user_messages', on_delete=models.CASCADE)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms
from . import models


class SelectRoom(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = ['name']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #  log the user in
            login(request, user)
            return redirect('chat:select')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('chat:select')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from . import forms
from .models import Room


# Create your views here.

@login_required(login_url="/accounts/login/")
def chat_room(request, room_name):
    if not Room.objects.filter(name=room_name).first():
        Room.objects.create(name=room_name)
    return render(request, 'chat/chatroom.html', {'room_name': room_name})


@login_required(login_url="/accounts/login/")
def select_room(request):
    if request.method == 'POST':
        form = forms.SelectRoom(request.POST)
        if form.is_valid():
            return redirect('chat:room', room_name=form.data['name'])
    else:
        form = forms.SelectRoom()
    return render(request, 'chat/selectroom.html', {'form': form})

core/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')


def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

chat/templates/chat/chatroom.html
{% extends 'base_layout.html' %}

{% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6">
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1" class="h4 pt-5">Chatroom</label>
                        <textarea class="form-control" id="chat-text" rows="10"></textarea><br>
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="input" type="text"></br>
                    </div>
                    <input class="btn btn-secondary btn-lg btn-block" id="submit" type="button" value="Send">
                </form>
            </div>
        </div>
    </div>

    {{ request.user.username|json_script:"user_username" }}
    {{ room_name|json_script:"room-name" }}
    <script>
        const user_username = JSON.parse(document.getElementById('user_username').textContent);
        document.querySelector('#submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'username': user_username,
                'action': "new_message"
            }));
            messageInputDom.value = '';
        };

        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://' +
            window.location.host +
            '/ws/chat/' +
            roomName +
            '/'
        );

        chatSocket.onopen = function(e) {
            fetchMessages();
        };

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            console.log(data)
            if (data['action'] === 'messages') {
              for (let i=0; i<data['messages'].length; i++) {
                insertMessage(data['messages'][i]);
              }
            } else if (data['action'] === 'new_message'){
              insertMessage(data['message']);
            }
        }
        function insertMessage(data) {
            document.querySelector('#chat-text').value += (data.username + ': ' + data.message + '\n')
        }

        function fetchMessages() {
          chatSocket.send(JSON.stringify({'action': 'fetch_messages',
          'room_name':roomName
           }));
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
{% endblock %}

chat/templates/chat/selectroom.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
        <h2>Insert the name of the ChatRoom</h2>
        <form class="site-form" action="{% url 'chat:select' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Select">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>About Us</h1>
    <p>We like django.</p>
</div>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <title>ChatRoom</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
{#        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}

    <!-- Bootstrap CSS -->
{#        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"#}
{#            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">#}
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'signup' %}"><img src="{% static 'logo1.jpg' %}" width="250"
                    height="100" alt="ChatRoom" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'chat:select' %}" class="highlight">Select Room</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    <li><a href="{% url 'chat:select' %}">Select Room</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
{#     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"#}
{#        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">#}
{#    </script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"#}
{#        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">#}
{#    </script>#}
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"#}
{#        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">#}
{#    </script>#}
    </body>
</html>